//! Serialized workflow execution with durable Linear receipts and conservative recovery.

use crate::{
    catalog::Catalog,
    model::{Fault, Outcome, Principal, Record, Result, array, require, text},
    records::{Snapshot, Store, content_hash, hash},
    rules,
};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::{collections::BTreeSet, sync::Arc};
use tokio::sync::Mutex;

/// Closed set of adapter effects generated by trusted workflow recipes.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Effect {
    /// Upsert one authenticated workflow record at a stable native URL.
    Record {
        /// Exact signed record.
        record: Record,
        /// Immutable URL captured at work creation.
        base_url: String,
    },
    /// Create a native work Issue using a reserved UUID.
    CreateIssue {
        /// Schema-checked IssueCreateInput built by the recipe.
        input: Value,
    },
    /// Change only explicitly managed Issue fields.
    UpdateIssue {
        /// Native Issue UUID.
        id: String,
        /// Narrow IssueUpdateInput.
        input: Value,
    },
    /// Create an epic Project with a reserved UUID.
    CreateProject {
        /// ProjectCreateInput.
        input: Value,
    },
    /// Project acceptance/status projection.
    UpdateProject {
        /// Native Project UUID.
        id: String,
        /// Narrow ProjectUpdateInput.
        input: Value,
    },
    /// Associate an epic Project with its product Initiative.
    LinkProject {
        /// InitiativeToProjectCreateInput with reserved UUID.
        input: Value,
    },
    /// Create a native draft or immutable snapshot.
    CreateDocument {
        /// DocumentCreateInput with exact intended content.
        input: Value,
    },
    /// Update a draft only after an exact current-content comparison.
    UpdateDocument {
        /// Native Document UUID.
        id: String,
        /// Title/content fields only.
        input: Value,
        /// Expected current native content digest.
        previous_hash: String,
    },
    /// Publish an immutable copy of an existing checked native draft.
    CopyDocument {
        /// Current draft ID.
        source_id: String,
        /// Reserved snapshot ID.
        id: String,
        /// Snapshot title.
        title: String,
        /// Product knowledge Project UUID.
        project_id: String,
    },
    /// Create readable human-facing progress or questions.
    CreateComment {
        /// CommentCreateInput with reserved UUID.
        input: Value,
    },
    /// Finalize new managed metadata using the actual URL returned by Linear.
    NewWork {
        /// Immutable work mapping; its URL placeholder is resolved before signing.
        identity: Record,
        /// Initial committed head.
        head: Box<Record>,
    },
    /// Verify a decision source before any owner decision record can be written.
    VerifyOwnerComment {
        /// Native comment ID.
        id: String,
        /// Exact owning work Issue.
        work_id: String,
        /// Unambiguous question token.
        decision_token: String,
        /// Explicit chosen option.
        decision_key: String,
        /// Allowed real owner identities.
        owner_ids: Vec<String>,
    },
}

/// Prepared immutable intent stored in its operation receipt before execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Plan {
    /// Existing work whose revision and scope authorize this intent, including creates.
    pub target_work_id: String,
    /// Fixed finite adapter operations, with all new IDs already reserved.
    pub effects: Vec<Effect>,
    /// Document references retained for compatibility with earlier pending recipes.
    pub documents: Vec<Record>,
    /// Exact result issued only after every effect is verified.
    pub result: Outcome,
    /// Original protected principal; rechecked on recovery.
    pub actor: Principal,
}

/// Shared gateway; requests retain no authoritative state after completion.
pub struct Gateway {
    /// Concrete Linear record backend.
    pub store: Store,
    /// Embedded schemas used for discovery and strict validation.
    pub catalog: Catalog,
    /// Process-local serialization prevents overlapping recipes in this single writer.
    writer: Mutex<()>,
}
impl Gateway {
    /// Construct a gateway without contacting Linear, allowing token-free MCP discovery.
    pub fn new(store: Store) -> Result<Arc<Self>> {
        Ok(Arc::new(Self {
            store,
            catalog: Catalog::new()?,
            writer: Mutex::new(()),
        }))
    }
    /// Execute a tool and convert all domain failures into structured MCP outcomes.
    pub async fn call(&self, p: &Principal, name: &str, args: Value) -> Outcome {
        let key = if name == "at_reconcile" && args["mode"] != "restore_projection" {
            args["operation_key"].as_str()
        } else {
            args["idempotency_key"].as_str()
        }
        .map(str::to_owned);
        match self.run(p, name, &args).await {
            Ok(result) => result,
            Err(error) => Outcome::failure(error, key),
        }
    }
    /// Validate before I/O, then serialize authoritative reads and writes for consistent local behavior.
    async fn run(&self, p: &Principal, name: &str, args: &Value) -> Result<Outcome> {
        let write = self.catalog.validate(name, p.role, args)?;
        let product = text(args, "product_id")?;
        require(
            (p.role == crate::model::Role::Owner && p.products.is_empty())
                || p.products.iter().any(|id| id == product),
            "OUT_OF_SCOPE",
            "Binding cannot access this product",
        )?;
        // ponytail: one gateway mutex; split by product if measured contention warrants it.
        let _guard = self.writer.lock().await;
        let snapshot = self.store.snapshot(product).await?;
        rules::authorize(&snapshot, p)?;
        if name == "at_reconcile" {
            return self.reconcile(p, &snapshot, args).await;
        }
        if !write {
            return self.read(p, &snapshot, name, args).await;
        }
        require(
            snapshot.config.payload["product_state"] == "active",
            "PRODUCT_CLOSED",
            "Product is not active",
        )?;
        let key = text(args, "idempotency_key")?;
        let digest = hash(args)?;
        if let Some(receipt) = snapshot
            .records
            .values()
            .find(|r| r.record_kind == "operation_receipt" && r.payload["idempotency_key"] == key)
        {
            require(
                receipt.payload["principal_id"] == p.id
                    && receipt.payload["tool"] == name
                    && receipt.payload["command_sha256"] == digest,
                "PAYLOAD_MISMATCH",
                "Idempotency key is already bound to another actor, tool or payload",
            )?;
            if receipt.payload["state"] == "committed" {
                let plan: Plan = serde_json::from_value(receipt.payload["plan"].clone())
                    .map_err(|_| Fault::new("SNAPSHOT_TAMPERED", "Saved plan is invalid"))?;
                rules::in_scope(
                    &snapshot,
                    p,
                    plan.result.data["work_id"].as_str().unwrap_or(product),
                )?;
                return serde_json::from_value(receipt.payload["result"].clone())
                    .map_err(|_| Fault::new("SNAPSHOT_TAMPERED", "Saved result is invalid"));
            }
            return Err(Fault::new(
                "OPERATION_IN_DOUBT",
                "Inspect this saved operation before resuming",
            )
            .uncertain());
        }
        require(
            snapshot.config.payload["pending_operation_key"].is_null(),
            "OPERATION_IN_DOUBT",
            "A pending product operation must be reconciled first",
        )?;
        require(
            !snapshot.records.values().any(|r| {
                r.record_kind == "operation_receipt"
                    && !matches!(r.payload["state"].as_str(), Some("committed" | "aborted"))
            }),
            "OPERATION_IN_DOUBT",
            "A prepared operation without a pending pointer must be reconciled first",
        )?;
        for team in array(&snapshot.config.payload, "team_ids") {
            let native = self
                .store
                .linear
                .object("QTeam", "team", team.as_str().unwrap_or(""))
                .await?;
            require(
                native["autoCloseParentIssues"] != true && native["autoCloseChildIssues"] != true,
                "UNSAFE_AUTOMATION",
                "Disable parent and child auto-close in the dedicated team before workflow writes",
            )?;
        }
        let mut plan = rules::plan(&snapshot, p, &self.store.signer, name, args)?;
        for record in &plan.documents {
            self.store.document(&snapshot, record).await?;
        }
        self.preflight(&mut plan, &snapshot).await?;
        self.prepare_execute(&snapshot, p, name, args, plan).await
    }
    /// Prepare and read back an exact intent and pending pointer before any domain effects.
    async fn prepare_execute(
        &self,
        snapshot: &Snapshot,
        p: &Principal,
        name: &str,
        args: &Value,
        plan: Plan,
    ) -> Result<Outcome> {
        let product = &snapshot.product;
        let key = text(args, "idempotency_key")?;
        let digest = hash(args)?;
        let receipt=self.store.signer.record(p,product,product,"operation_receipt",json!({"tool":name,"idempotency_key":key,"command_sha256":digest,"principal_id":p.id,"command":args,"state":"prepared","plan":plan,"steps":vec!["planned";plan.effects.len()]}),None)?;
        let base = text(&snapshot.config.payload, "record_base_url")?;
        self.store
            .put(&receipt, base)
            .await
            .map_err(Fault::uncertain)?;
        let mut config = snapshot.config.clone();
        config.payload["pending_operation_key"] = json!(key);
        config.revision += 1;
        self.store.signer.seal(&mut config)?;
        self.store
            .put(&config, base)
            .await
            .map_err(Fault::uncertain)?;
        self.execute(snapshot, config, receipt).await
    }
    /// Resolve draft copies and owner proof reads before prepare; no external mutation is made here.
    async fn preflight(&self, plan: &mut Plan, snapshot: &Snapshot) -> Result<()> {
        for effect in &mut plan.effects {
            match effect.clone() {
                Effect::CopyDocument {
                    source_id,
                    id,
                    title,
                    project_id,
                } => {
                    let source = self
                        .store
                        .linear
                        .object("QDocument", "document", &source_id)
                        .await?;
                    require(
                        source["project"]["id"] == project_id,
                        "DOCUMENT_EDIT_CONFLICT",
                        "Draft changed before publication",
                    )?;
                    *effect = Effect::CreateDocument {
                        input: json!({"id":id,"title":title,"content":source["content"],"projectId":project_id}),
                    };
                }
                Effect::UpdateDocument {
                    id, previous_hash, ..
                } => {
                    let source = self
                        .store
                        .linear
                        .object("QDocument", "document", &id)
                        .await?;
                    require(
                        source["project"]["id"] == snapshot.config.payload["general_project_id"],
                        "OUT_OF_SCOPE",
                        "Draft is outside the product",
                    )?;
                    require(
                        previous_hash.is_empty()
                            || content_hash(source["content"].as_str().unwrap_or(""))
                                == previous_hash,
                        "DOCUMENT_EDIT_CONFLICT",
                        "Draft changed since it was read",
                    )?;
                    if let Effect::UpdateDocument { previous_hash, .. } = effect {
                        *previous_hash = content_hash(source["content"].as_str().unwrap_or(""));
                    }
                }
                Effect::VerifyOwnerComment { .. } => {
                    self.verify(effect).await?;
                }
                _ => {}
            }
        }
        // Validate the complete prepared receipt size before the first prepare write.
        require(
            serde_json::to_vec(plan).unwrap().len() < 220 * 1024,
            "RECORD_TOO_LARGE",
            "Operation exceeds the provisional receipt size cap; split the input",
        )
    }
    /// Persist progress before each dispatched effect and verify every effect before commit.
    async fn execute(
        &self,
        s: &Snapshot,
        mut config: Record,
        mut receipt: Record,
    ) -> Result<Outcome> {
        let base = text(&config.payload, "record_base_url")?.to_owned();
        let plan: Plan = serde_json::from_value(receipt.payload["plan"].clone())
            .map_err(|_| Fault::new("SNAPSHOT_TAMPERED", "Invalid operation recipe"))?;
        for (i, effect) in plan.effects.iter().enumerate() {
            let state = receipt.payload["steps"][i].as_str().unwrap_or("invalid");
            if state == "done" {
                self.verify(effect).await.map_err(Fault::uncertain)?;
                continue;
            }
            if state == "started" {
                match self.verify(effect).await {
                    Ok(()) => {}
                    // One writer owns this pending intent. A recorded upsert repeats the same
                    // reserved ID and content; resource creates remain unresolved when absent.
                    Err(error)
                        if error.code == "OPERATION_IN_DOUBT"
                            && matches!(effect, Effect::Record { .. }) =>
                    {
                        self.apply(effect).await.map_err(Fault::uncertain)?;
                    }
                    Err(error) => return Err(error.uncertain()),
                }
            } else {
                require(
                    state == "planned",
                    "SNAPSHOT_TAMPERED",
                    "Invalid effect state",
                )?;
                receipt.payload["state"] = json!("applying");
                receipt.payload["steps"][i] = json!("started");
                receipt.revision += 1;
                self.store.signer.seal(&mut receipt)?;
                self.store
                    .put(&receipt, &base)
                    .await
                    .map_err(Fault::uncertain)?;
                if let Effect::Record { record, .. } = effect
                    && record.record_kind == "work_head"
                    && let Some(work) = s.works.get(&record.work_id)
                {
                    let native = self
                        .store
                        .linear
                        .object("QIssue", "issue", &record.work_id)
                        .await
                        .map_err(Fault::uncertain)?;
                    require(
                        native["project"]["id"] == work.identity.payload["native_project_id"]
                            && native["parent"]["id"] == work.identity.payload["native_parent_id"]
                            && native["state"]["id"] == record.payload["native_state_id"],
                        "STRUCTURE_DRIFT",
                        "Protected native fields changed before committing the head",
                    )
                    .map_err(Fault::uncertain)?;
                }
                self.apply(effect).await.map_err(Fault::uncertain)?;
                if !matches!(effect, Effect::Record { .. } | Effect::NewWork { .. }) {
                    self.verify(effect).await.map_err(Fault::uncertain)?;
                }
            }
            receipt.payload["steps"][i] = json!("done");
            receipt.revision += 1;
            self.store.signer.seal(&mut receipt)?;
            self.store
                .put(&receipt, &base)
                .await
                .map_err(Fault::uncertain)?;
        }
        // The result is retained even if the final response or pending clear is lost.
        receipt.payload["state"] = json!("committed");
        receipt.payload["result"] = serde_json::to_value(&plan.result).unwrap();
        receipt.revision += 1;
        self.store.signer.seal(&mut receipt)?;
        self.store
            .put(&receipt, &base)
            .await
            .map_err(Fault::uncertain)?;
        config.payload["pending_operation_key"] = Value::Null;
        config.revision += 1;
        self.store.signer.seal(&mut config)?;
        self.store
            .put(&config, &base)
            .await
            .map_err(Fault::uncertain)?;
        let _ = s;
        Ok(plan.result)
    }
    /// Perform exactly one finite trusted adapter action, never an operation supplied by the model.
    async fn apply(&self, effect: &Effect) -> Result<()> {
        let api = &self.store.linear;
        match effect {
            Effect::Record { record, base_url } => return self.store.put(record, base_url).await,
            Effect::CreateIssue { input } => {
                api.call("MCreateIssue", json!({"input":input})).await?;
            }
            Effect::UpdateIssue { id, input } => {
                api.call("MUpdateIssue", json!({"id":id,"input":input}))
                    .await?;
            }
            Effect::CreateProject { input } => {
                api.call("MCreateProject", json!({"input":input})).await?;
            }
            Effect::UpdateProject { id, input } => {
                api.call("MUpdateProject", json!({"id":id,"input":input}))
                    .await?;
            }
            Effect::LinkProject { input } => {
                api.call("MLinkProjectToInitiative", json!({"input":input}))
                    .await?;
            }
            Effect::CreateDocument { input } => {
                api.call("MCreateDocument", json!({"input":input})).await?;
            }
            Effect::UpdateDocument {
                id,
                input,
                previous_hash,
            } => {
                let old = api.object("QDocument", "document", id).await?;
                require(
                    content_hash(old["content"].as_str().unwrap_or("")) == *previous_hash,
                    "DOCUMENT_EDIT_CONFLICT",
                    "Draft changed before the write",
                )?;
                api.call("MUpdateDocument", json!({"id":id,"input":input}))
                    .await?;
            }
            Effect::CreateComment { input } => {
                api.call("MCreateComment", json!({"input":input})).await?;
            }
            Effect::NewWork { identity, head } => {
                let native = api.object("QIssue", "issue", &identity.work_id).await?;
                let url = text(&native, "url")?;
                let mut identity = identity.clone();
                identity.payload["record_base_url"] = json!(url);
                self.store.signer.seal(&mut identity)?;
                self.store.put(&identity, url).await?;
                self.store.put(head, url).await?;
            }
            Effect::VerifyOwnerComment { .. } => return self.verify(effect).await,
            Effect::CopyDocument { .. } => {
                return Err(Fault::new("SCHEMA_UNSUPPORTED", "Unresolved copy effect"));
            }
        }
        Ok(())
    }
    /// Observe an effect by its exact reserved ID; a missing in-flight object is never recreated here.
    async fn verify(&self, effect: &Effect) -> Result<()> {
        let api = &self.store.linear;
        match effect {
            Effect::Record { record, .. } => self.store.verify(record).await,
            Effect::CreateIssue { input } => {
                let native = api.object("QIssue", "issue", text(input, "id")?).await?;
                for (field, path) in [
                    ("title", "/title"),
                    ("projectId", "/project/id"),
                    ("parentId", "/parent/id"),
                    ("stateId", "/state/id"),
                    ("teamId", "/team/id"),
                ] {
                    require(
                        native.pointer(path).unwrap_or(&Value::Null) == &input[field],
                        "STRUCTURE_DRIFT",
                        format!("Created issue differs in {field}"),
                    )?;
                }
                Ok(())
            }
            Effect::UpdateIssue { id, input } => {
                let native = api.object("QIssue", "issue", id).await?;
                for (field, path) in [
                    ("stateId", "/state/id"),
                    ("assigneeId", "/assignee/id"),
                    ("delegateId", "/delegate/id"),
                ] {
                    if let Some(v) = input.get(field) {
                        require(
                            native.pointer(path) == Some(v),
                            "STRUCTURE_DRIFT",
                            format!("Issue projection differs in {field}"),
                        )?;
                    }
                }
                Ok(())
            }
            Effect::CreateProject { input } => {
                let native = api
                    .object("QProject", "project", text(input, "id")?)
                    .await?;
                require(
                    native["name"] == input["name"],
                    "STRUCTURE_DRIFT",
                    "Created project differs",
                )
            }
            Effect::UpdateProject { id, input } => {
                let native = api.object("QProject", "project", id).await?;
                require(
                    native["status"]["id"] == input["statusId"],
                    "STRUCTURE_DRIFT",
                    "Project projection differs",
                )
            }
            Effect::LinkProject { input } => {
                let native = api
                    .object("QInitiativeLink", "initiativeToProject", text(input, "id")?)
                    .await?;
                require(
                    native["initiative"]["id"] == input["initiativeId"]
                        && native["project"]["id"] == input["projectId"],
                    "STRUCTURE_DRIFT",
                    "Project/Initiative association differs",
                )
            }
            Effect::CreateDocument { input } => {
                let native = api
                    .object("QDocument", "document", text(input, "id")?)
                    .await?;
                require(
                    native["content"] == input["content"]
                        && native["title"] == input["title"]
                        && native["project"]["id"] == input["projectId"],
                    "SNAPSHOT_TAMPERED",
                    "Document round-trip differs from the prepared snapshot; inspect canonical normalization",
                )
            }
            Effect::UpdateDocument { id, input, .. } => {
                let native = api.object("QDocument", "document", id).await?;
                require(
                    native["content"] == input["content"] && native["title"] == input["title"],
                    "DOCUMENT_EDIT_CONFLICT",
                    "Draft read-back differs",
                )
            }
            Effect::CreateComment { input } => {
                let native = api
                    .object("QComment", "comment", text(input, "id")?)
                    .await?;
                require(
                    native["body"] == input["body"] && native["issue"]["id"] == input["issueId"],
                    "LINEAR_PARTIAL_ERROR",
                    "Comment read-back differs",
                )
            }
            Effect::NewWork { identity, head } => {
                let native = api
                    .object("QAttachmentById", "attachment", &identity.record_id)
                    .await?;
                let saved = self
                    .store
                    .parse(&native, &identity.product_id)?
                    .ok_or_else(|| Fault::new("RECORD_MISSING", "New work identity is missing"))?;
                let mut expected = identity.clone();
                expected.payload["record_base_url"] = saved.payload["record_base_url"].clone();
                self.store.signer.seal(&mut expected)?;
                require(
                    saved == expected,
                    "STRUCTURE_DRIFT",
                    "New work mapping differs",
                )?;
                let native = api
                    .object("QAttachmentById", "attachment", &head.record_id)
                    .await?;
                require(
                    self.store.parse(&native, &head.product_id)?.as_ref() == Some(head.as_ref()),
                    "STRUCTURE_DRIFT",
                    "Initial work head differs",
                )
            }
            Effect::VerifyOwnerComment {
                id,
                work_id,
                decision_token,
                decision_key,
                owner_ids,
            } => {
                let comment = api.object("QComment", "comment", id).await?;
                let body = comment["body"].as_str().unwrap_or("");
                require(
                    comment["issue"]["id"] == *work_id
                        && owner_ids.iter().any(|id| comment["user"]["id"] == *id)
                        && body
                            .lines()
                            .any(|line| line.trim() == format!("{decision_token} {decision_key}")),
                    "UNTRUSTED_OWNER_SOURCE",
                    "Owner comment must contain the exact decision token and option on one line",
                )
            }
            Effect::CopyDocument { .. } => {
                Err(Fault::new("SCHEMA_UNSUPPORTED", "Unresolved copy effect"))
            }
        }
    }
    /// Inspect or safely resume a saved operation; inspection never creates a new receipt.
    async fn reconcile(&self, p: &Principal, s: &Snapshot, args: &Value) -> Result<Outcome> {
        if args["mode"] == "restore_projection" {
            return self.restore_projection(p, s, args).await;
        }
        let key = args["operation_key"]
            .as_str()
            .or(s.config.payload["pending_operation_key"].as_str())
            .ok_or_else(|| Fault::new("RECORD_MISSING", "No operation key or pending operation"))?;
        let receipt = s
            .records
            .values()
            .find(|r| r.record_kind == "operation_receipt" && r.payload["idempotency_key"] == key)
            .ok_or_else(|| Fault::new("RECORD_MISSING", "Operation receipt is missing"))?
            .clone();
        if args["mode"] == "inspect" {
            return Ok(Outcome::ok(
                json!({"operation_key":key,"state":receipt.payload["state"],"tool":receipt.payload["tool"],"steps":receipt.payload["steps"],"principal_id":receipt.payload["principal_id"],"result":receipt.payload["result"]}),
            ));
        }
        text(args, "idempotency_key")?;
        if let Some(revision) = args["expected"]["work_revision"].as_u64() {
            require(
                revision == s.work(&s.product)?.head.revision,
                "STALE_CONTEXT",
                "Product changed; refresh context",
            )?;
        }
        let mut config = s.config.clone();
        if config.payload["pending_operation_key"].is_null()
            && receipt.payload["state"] == "prepared"
            && array(&receipt.payload, "steps")
                .iter()
                .all(|v| v == "planned")
        {
            config.payload["pending_operation_key"] = json!(key);
            config.revision += 1;
            self.store.signer.seal(&mut config)?;
            self.store
                .put(&config, text(&config.payload, "record_base_url")?)
                .await
                .map_err(Fault::uncertain)?;
        }
        require(
            config.payload["pending_operation_key"] == key,
            "OPERATION_IN_DOUBT",
            "Receipt is not the current pending intent",
        )?;
        let plan: Plan = serde_json::from_value(receipt.payload["plan"].clone())
            .map_err(|_| Fault::new("SNAPSHOT_TAMPERED", "Invalid saved recipe"))?;
        rules::authorize(s, &plan.actor)?;
        rules::in_scope(s, &plan.actor, &plan.target_work_id)?;
        if receipt.payload["state"] == "committed" {
            for effect in &plan.effects {
                self.verify(effect).await.map_err(Fault::uncertain)?;
            }
            let mut config = s.config.clone();
            config.payload["pending_operation_key"] = Value::Null;
            config.revision += 1;
            self.store.signer.seal(&mut config)?;
            self.store
                .put(&config, text(&config.payload, "record_base_url")?)
                .await?;
            return Ok(plan.result);
        }
        for doc in &plan.documents {
            self.store.document(s, doc).await?;
        }
        self.execute(s, config, receipt).await
    }
    /// Restore the recorded issue status at an authenticated controller's explicit request.
    async fn restore_projection(
        &self,
        p: &Principal,
        s: &Snapshot,
        args: &Value,
    ) -> Result<Outcome> {
        let key = text(args, "idempotency_key")?;
        if let Some(receipt) = s
            .records
            .values()
            .find(|r| r.record_kind == "operation_receipt" && r.payload["idempotency_key"] == key)
        {
            require(
                receipt.payload["tool"] == "at_reconcile"
                    && receipt.payload["principal_id"] == p.id
                    && receipt.payload["command_sha256"] == hash(args)?,
                "PAYLOAD_MISMATCH",
                "Projection repair key is bound to another intent",
            )?;
            if receipt.payload["state"] == "committed" {
                return serde_json::from_value(receipt.payload["result"].clone()).map_err(|_| {
                    Fault::new("SNAPSHOT_TAMPERED", "Saved repair result is invalid")
                });
            }
            return Err(Fault::new(
                "OPERATION_IN_DOUBT",
                "Inspect the saved projection repair before resuming",
            )
            .uncertain());
        }
        let id = text(args, "work_id")?;
        let work = s.work(id)?;
        if let Some(revision) = args["expected"]["work_revision"].as_u64() {
            require(
                revision == work.head.revision,
                "STALE_CONTEXT",
                "Work changed; refresh context",
            )?;
        }
        require(
            s.config.payload["pending_operation_key"].is_null(),
            "OPERATION_IN_DOUBT",
            "Reconcile pending effects first",
        )?;
        require(
            work.native["project"]["id"] == work.identity.payload["native_project_id"]
                && work.native["parent"]["id"] == work.identity.payload["native_parent_id"],
            "STRUCTURE_DRIFT",
            "Status repair cannot repair changed work membership",
        )?;
        let effect = Effect::UpdateIssue {
            id: id.into(),
            input: json!({"stateId":work.head.payload["native_state_id"]}),
        };
        let mut result = Outcome::ok(json!({"work_id":id,"restored":true}));
        result.status = "committed".into();
        result.operation_key = Some(text(args, "idempotency_key")?.into());
        self.prepare_execute(
            s,
            p,
            "at_reconcile",
            args,
            Plan {
                target_work_id: id.into(),
                effects: vec![effect],
                documents: vec![],
                result,
                actor: p.clone(),
            },
        )
        .await
    }
    /// Return scoped context and guidance without creating assignments or changing native data.
    async fn read(&self, p: &Principal, s: &Snapshot, name: &str, args: &Value) -> Result<Outcome> {
        match name {
            "at_resume" => {
                let mut items = vec![];
                let requested = args["work_id"].as_str();
                if let Some(id) = requested {
                    rules::in_scope(s, p, id)?;
                }
                for (id, work) in &s.works {
                    if requested.is_some_and(|root| !s.within(id, root))
                        || rules::in_scope(s, p, id).is_err()
                    {
                        continue;
                    }
                    let drift = rules::no_drift(s, id).err();
                    items.push(json!({"work_id":id,"title":work.native["title"],"url":work.native["url"],"kind":work.identity.payload["kind"],"state":work.head.payload["state"],"activity":rules::activity(s,id),"native_status":work.native["state"],"version":{"work_revision":work.head.revision,"plan_hash":work.head.payload["plan_hash"]},"assignments":array(&work.head.payload,"assignment_ids").iter().filter_map(|id|s.records.get(id.as_str()?)).map(|r|json!({"id":r.record_id,"principal_id":r.payload["principal_id"],"generation":r.payload["generation"],"status":r.payload["status"],"runtime_state":r.payload["latest_attempt_id"].as_str().and_then(|id|s.records.get(id)).map(|r|r.payload["observation"].clone()).unwrap_or(json!({"state":"unknown","writer_state":"unknown"}))})).collect::<Vec<_>>(),"drift":drift.map(|e|e.code)}));
                }
                let mut out = self.page(
                    p,
                    s,
                    args,
                    json!({"items":items}),
                    args["limit"].as_u64().unwrap_or(10) as usize,
                    false,
                )?;
                out.data["pending_operation_key"] =
                    s.config.payload["pending_operation_key"].clone();
                out.data["product_revision"] = json!(s.work(&s.product)?.head.revision);
                let pending = s
                    .records
                    .values()
                    .filter(|r| {
                        r.record_kind == "operation_receipt"
                            && !matches!(r.payload["state"].as_str(), Some("committed" | "aborted"))
                    })
                    .map(|r| r.payload["idempotency_key"].clone())
                    .collect::<Vec<_>>();
                out.incomplete |= !pending.is_empty();
                if p.role.controls() {
                    out.data["pending_operations"] = json!(pending);
                }
                Ok(out)
            }
            "at_context" => {
                let section = text(args, "section")?;
                let count = ["work_id", "record_id", "publication_id"]
                    .iter()
                    .filter(|key| args[**key].is_string())
                    .count();
                require(
                    count == 1,
                    "INVALID_INPUT",
                    "Context requires exactly one target",
                )?;
                let value = if let Some(id) = args["work_id"].as_str() {
                    rules::in_scope(s, p, id)?;
                    rules::no_drift(s, id)?;
                    let work = s.work(id)?;
                    match section {
                        "work" => {
                            json!({"native":work.native,"identity":work.identity.payload,"head":work.head.payload,"revision":work.head.revision,"activity":rules::activity(s,id)})
                        }
                        "plan" | "inputs" => {
                            let id = work.head.payload["plan_record_id"]
                                .as_str()
                                .ok_or_else(|| Fault::new("PLAN_REQUIRED", "No published plan"))?;
                            let plan = s.record(id, Some("plan"))?;
                            self.store.document(s, plan).await?;
                            if section == "inputs" {
                                plan.payload["inputs"].clone()
                            } else {
                                serde_json::to_value(plan).unwrap()
                            }
                        }
                        "review" => {
                            let id = text(&work.head.payload, "review_case_id")?;
                            serde_json::to_value(s.record(id, Some("review_case"))?).unwrap()
                        }
                        "history" => json!(
                            s.records
                                .values()
                                .filter(|r| r.work_id == id && r.record_kind != "operation_receipt")
                                .collect::<Vec<_>>()
                        ),
                        _ => {
                            return Err(Fault::new(
                                "INVALID_INPUT",
                                "This section requires a record target",
                            ));
                        }
                    }
                } else {
                    let id = args["record_id"]
                        .as_str()
                        .or(args["publication_id"].as_str())
                        .unwrap();
                    let record = s.record(id, None)?;
                    can_read_record(s, p, record)?;
                    if section == "publication" {
                        require(
                            s.is_committed(record),
                            "KNOWLEDGE_UNPUBLISHED",
                            "Publication has not committed",
                        )?;
                        require(
                            record.record_kind == "publication",
                            "INVALID_INPUT",
                            "Expected a publication",
                        )?;
                        self.store.document(s, record).await?
                    } else {
                        require(
                            section == "record",
                            "INVALID_INPUT",
                            "Record targets require section=record",
                        )?;
                        if record.payload["content_hash"].is_string() {
                            self.store.document(s, record).await?;
                        }
                        if record.record_kind == "note" {
                            let draft = self.store.document(s, record).await?;
                            json!({"record":record,"content_hash":content_hash(draft["content"].as_str().unwrap_or("")),"draft":draft})
                        } else {
                            serde_json::to_value(record).unwrap()
                        }
                    }
                };
                let mut outcome = self.page(
                    p,
                    s,
                    args,
                    value,
                    args["max_chars"].as_u64().unwrap_or(16000) as usize,
                    true,
                )?;
                if let Some(id) = args["work_id"].as_str() {
                    let head = &s.work(id)?.head;
                    outcome.version = json!({"work_revision":head.revision});
                    if head.payload["plan_hash"].is_string() {
                        outcome.version["plan_hash"] = head.payload["plan_hash"].clone();
                    }
                    if let Some(generation) = p.generation {
                        outcome.version["assignment_generation"] = json!(generation);
                    }
                }
                Ok(outcome)
            }
            "at_search" => {
                let mut items = vec![];
                let query = text(args, "query")?;
                let kind = text(args, "kind")?;
                let mut project_ids: BTreeSet<_> = s
                    .works
                    .values()
                    .filter_map(|w| {
                        w.identity.payload["native_project_id"]
                            .as_str()
                            .map(str::to_owned)
                    })
                    .collect();
                project_ids.insert(text(&s.config.payload, "general_project_id")?.into());
                for operation in if kind == "both" {
                    vec!["QSearchIssues", "QSearchDocuments"]
                } else if kind == "work" {
                    vec!["QSearchIssues"]
                } else {
                    vec!["QSearchDocuments"]
                } {
                    let field = if operation == "QSearchIssues" {
                        "searchIssues"
                    } else {
                        "searchDocuments"
                    };
                    let mut after = Value::Null;
                    let mut complete = false;
                    for _ in 0..10 {
                        let data=self.store.linear.call(operation,json!({"term":query,"filter":{"project":{"id":{"in":project_ids}}},"first":50,"after":after})).await?;
                        let conn = &data[field];
                        for native in array(conn, "nodes") {
                            let id = text(native, "id")?;
                            if operation == "QSearchIssues" {
                                if let Some(work) = s.works.get(id)
                                    && rules::in_scope(s, p, id).is_ok()
                                {
                                    items.push(json!({"id":id,"title":native["title"],"url":native["url"],"kind":"work","state":work.head.payload["state"]}));
                                }
                            } else {
                                for publication in s.records.values().filter(|r| {
                                    r.record_kind == "publication"
                                        && s.is_committed(r)
                                        && r.payload["document_id"] == id
                                }) {
                                    if can_read_record(s, p, publication).is_ok() {
                                        let note = s.record(
                                            text(&publication.payload, "note_id")?,
                                            Some("note"),
                                        )?;
                                        let historical = note.payload["latest_publication_id"]
                                            != publication.record_id;
                                        if args["include_history"] == true || !historical {
                                            items.push(json!({"id":id,"title":native["title"],"url":native["url"],"kind":"knowledge","publication_id":publication.record_id,"historical":historical}));
                                        }
                                    }
                                }
                            }
                        }
                        if conn["pageInfo"]["hasNextPage"] == false {
                            complete = true;
                            break;
                        }
                        let next = conn["pageInfo"]["endCursor"].clone();
                        require(
                            next.is_string() && next != after,
                            "INCOMPLETE_DATA",
                            "Search pagination did not advance",
                        )?;
                        after = next;
                    }
                    require(
                        complete,
                        "INCOMPLETE_DATA",
                        "Search page budget exhausted; narrow the query",
                    )?;
                }
                self.page(
                    p,
                    s,
                    args,
                    json!({"items":items}),
                    args["limit"].as_u64().unwrap_or(10) as usize,
                    false,
                )
            }
            _ => Err(Fault::new("UNKNOWN_TOOL", "Unknown read tool")),
        }
    }
    /// Slice results with a signed actor/query/content-bound cursor and explicit incompleteness.
    fn page(
        &self,
        p: &Principal,
        s: &Snapshot,
        args: &Value,
        value: Value,
        limit: usize,
        chars: bool,
    ) -> Result<Outcome> {
        let digest = hash(&value)?;
        let mut query = args.clone();
        query.as_object_mut().unwrap().remove("cursor");
        let query_hash = hash(&query)?;
        let offset = if let Some(cursor) = args["cursor"].as_str() {
            let c = self.store.signer.decode_cursor(cursor)?;
            require(
                c["actor"] == p.id
                    && c["product"] == s.product
                    && c["digest"] == digest
                    && c["query"] == query_hash,
                "STALE_CONTEXT",
                "Continuation no longer matches its source or binding",
            )?;
            c["offset"]
                .as_u64()
                .ok_or_else(|| Fault::new("STALE_CONTEXT", "Invalid continuation offset"))?
                as usize
        } else {
            0
        };
        let (data, end, total) = if chars {
            let encoded = serde_json::to_string(&value).unwrap();
            let symbols: Vec<_> = encoded.chars().collect();
            require(
                offset <= symbols.len(),
                "STALE_CONTEXT",
                "Continuation exceeds content",
            )?;
            let end = (offset + limit).min(symbols.len());
            (
                json!({"content":symbols[offset..end].iter().collect::<String>(),"content_digest":digest,"encoding":"json"}),
                end,
                symbols.len(),
            )
        } else {
            let items = array(&value, "items");
            require(
                offset <= items.len(),
                "STALE_CONTEXT",
                "Continuation exceeds results",
            )?;
            let end = (offset + limit).min(items.len());
            (
                json!({"items":&items[offset..end],"content_digest":digest}),
                end,
                items.len(),
            )
        };
        let mut out = Outcome::ok(data);
        out.incomplete = end < total;
        if out.incomplete {
            out.continuation=Some(self.store.signer.cursor(&json!({"actor":p.id,"product":s.product,"digest":digest,"query":query_hash,"offset":end}))?);
        }
        Ok(out)
    }
}

/// Permit knowledge through scope, associations, or exact input/contract pins in authorized plan history.
fn can_read_record(s: &Snapshot, p: &Principal, r: &Record) -> Result<()> {
    if rules::in_scope(s, p, &r.work_id).is_ok() {
        return Ok(());
    }
    if matches!(r.record_kind.as_str(), "publication" | "note") {
        if !s.is_committed(r) {
            return Err(Fault::new(
                "OUT_OF_SCOPE",
                "Knowledge is not committed for this binding",
            ));
        }
        if array(&r.payload, "associations")
            .iter()
            .filter_map(|a| a["work_id"].as_str())
            .any(|id| rules::in_scope(s, p, id).is_ok())
        {
            return Ok(());
        }
        for plan in s.records.values().filter(|r| {
            r.record_kind == "plan"
                && s.is_committed(r)
                && rules::in_scope(s, p, &r.work_id).is_ok()
        }) {
            if array(&plan.payload, "inputs")
                .iter()
                .chain(
                    array(&plan.payload, "contracts")
                        .iter()
                        .map(|contract| &contract["source"]),
                )
                .any(|pin| pin["kind"] == "linear_publication" && pin["id"] == r.record_id)
            {
                return Ok(());
            }
        }
    }
    Err(Fault::new(
        "OUT_OF_SCOPE",
        "Record is outside the binding's context",
    ))
}
